export const surpriseMePrompts = [
  "A tribal design of a tiger's face with sharp lines and bold colors",
"A delicate floral design featuring cherry blossom branches",
"A black and gray realistic eagle design with its wings spread",
"A colorful tropical bird design with abstract shapes and patterns",
"A mythical phoenix design with flames and intricate details",
"A simple yet elegant infinity symbol design with a heart incorporated",
"An edgy snake design with geometric shapes and a skull",
"A surrealistic design of a clock melting with flowers growing out of it",
"A watercolor forest design featuring a bear and a deer",
"A whimsical design of a unicorn with rainbow-colored mane and tail",
"A steampunk-style design of a mechanical owl with intricate gears and cogs",
"A whimsical design of a mermaid sitting on a rock, gazing at the moon",
"A realistic lion design with a fierce expression and a flowing mane",
"A mandala-style design of a lotus flower with abstract patterns and shapes",
"A minimalist design of a palm tree with a sunset in the background",
"A watercolor-style design of a hummingbird hovering near a blooming flower",
"An abstract design of a tiger with bold lines and vibrant colors",
"A realistic design of a wolf howling at the moon with a forest in the background",
"A delicate design of a butterfly with intricate details and soft colors",
"A surrealistic design of a snake with a bird's head and wings"
];
